import Config

# Configure your database
config :shopify_whatsapp, ShopifyWhatsapp.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "shopify_whatsapp_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :shopify_whatsapp, ShopifyWhatsappWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IEJAc3JyiGq6Du6ecuWtRmBOHC1XmaFuLw1ncZQ0x10wImUGNN9qO6gkCiLFHliD",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :shopify_whatsapp, ShopifyWhatsappWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/shopify_whatsapp_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :shopify_whatsapp, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Shopify API configuration
# NOTE: Replace with actual values from Shopify Partner dashboard
config :shopify_whatsapp,
  shopify_api_key: System.get_env("SHOPIFY_API_KEY") || "dev_api_key",
  shopify_api_secret: System.get_env("SHOPIFY_API_SECRET") || "dev_api_secret",
  shopify_webhook_secret: System.get_env("SHOPIFY_WEBHOOK_SECRET") || "dev_webhook_secret",
  app_host: "localhost:4000",
  https?: false

# WhatsApp configuration
config :shopify_whatsapp,
  whatsapp_base_url: System.get_env("WHATSAPP_BASE_URL") || "https://graph.facebook.com/v19.0",
  whatsapp_phone_id: System.get_env("WHATSAPP_PHONE_ID"),
  whatsapp_access_token: System.get_env("WHATSAPP_ACCESS_TOKEN")

# Webhook configuration
config :shopify_whatsapp,
  webhook_base_url: System.get_env("WEBHOOK_BASE_URL") || "http://localhost:4000"

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Oban background job configuration
config :shopify_whatsapp, Oban,
  repo: ShopifyWhatsapp.Repo,
  queues: [default: 10, shopify_sync: 5, whatsapp: 5],
  prefix: "oban",
  crontab: false,
  log: :debug

# Cloak encryption key for development (32 bytes base64 encoded)
config :shopify_whatsapp, :cloak_key, "DKbCL9Ix5w6uNV6xIZ8lHJ8LNLoC0P0BWyxIl3GIG8A="

# Cloak vault configuration with cipher
config :shopify_whatsapp, ShopifyWhatsapp.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1",
       key: Base.decode64!("DKbCL9Ix5w6uNV6xIZ8lHJ8LNLoC0P0BWyxIl3GIG8A="),
       iv_length: 12}
  ]
